apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: stock-db:5432
    database: stocktrading
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: stocktrading
      defaultBucket: metrics
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
    editable: true